[project]
name = "pai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "prompt-toolkit>=3.0.51",
    "toml>=0.10.2",
    "typer>=0.16.0",
    "ulid-py>=1.1.0",
    "jinja2>=3.1.4",
]



[project.scripts]
pai = "pai.pai:main"

[tool.hatch.build.targets.wheel]
packages = ["pai/"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

